# -*- coding: utf-8 -*-
"""bot_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1zg3uRWycLXNuRgcmSndoul-KTy4Hr0
"""

!pip install telebot

!pip install git+https://github.com/openai/whisper.git

from pathlib import Path
import os

!pip install moviepy

import moviepy.editor as me

import whisper

model = whisper.load_model('large')

#model_3 = whisper.load_model(name='/content/drive/MyDrive/models/large-v3.pt')

import telebot
from telebot import  types

bot= telebot.TeleBot('YOUR TOKEN')

@bot.message_handler(commands=['start'])
def send_welcom(message):
    bot.reply_to(message , 'welcome to this bot ')
    menu2 = types.ReplyKeyboardMarkup(resize_keyboard=True)
    item4= types.KeyboardButton("video")
    item5 = types.KeyboardButton("voice")
    menu2.add(item4 , item5)
    bot.send_message(message.chat.id ,"chose one", reply_markup=menu2)

@bot.message_handler(func= lambda message : True)
def handeling_other_message(message):
    if message.text =="vedeo":
        bot.send_message(message.chat.id , "send  a one video")
    elif message.text =="voice":
          bot.send_message(message.chat.id , "send  a one voice")

@bot.message_handler(content_types=[ 'video']) # list relevant content types
def handle_video(message):
    video_info = message.video
    file_id = video_info.file_id
    file_info = bot.get_file(file_id)
    downloaded_file = bot.download_file(file_info.file_path)
    with open(f"{file_id}.mp4", 'wb') as new_file:
          new_file.write(downloaded_file)
    p1=f"{file_id}.mp4"
    bot.reply_to(message, "ویدیو با موفقیت ذخیره شد.")
    bot.reply_to(message, "درحال پردازش")
    path1 = os.path.abspath(p1)
    cv_video = me.VideoFileClip(p1)
    cv_audio=cv_video.audio
    a=cv_audio.write_audiofile('a1.mp3')
    path1=os.path.abspath('a1.mp3')
    result = model.transcribe(path1)
    send = result["text"]
    print(send)
    bot.send_message(message.chat.id  , send)

@bot.message_handler(content_types=[ 'audio'])
def handle_audio(message):
    audio_info = message.audio
    file_id = audio_info.file_id
    file_info = bot.get_file(file_id)
    downloaded_file = bot.download_file(file_info.file_path)
    with open(f"{file_id}.Mp3", 'wb') as new_file:
          new_file.write(downloaded_file)
    bot.reply_to(message, "صدا با موفقیت ذخیره شد.")
    bot.reply_to(message, "درحال پردازش")
    p2=  f"{file_id}.Mp3"
    result = model.transcribe(p2)
    send = result["text"]
    print(send)
    bot.send_message(message.chat.id  , send)

@bot.message_handler(content_types=['voice'])
def handle_voice(message):
    file_info = bot.get_file(message.voice.file_id)
    downloaded_file = bot.download_file(file_info.file_path)
    file_name = f"{message.voice.file_id}.ogg"
    with open(file_name, 'wb') as new_file:
        new_file.write(downloaded_file)
    bot.reply_to(message, "ویس با موفقیت ذخیره شد.")
    bot.reply_to(message, "درحال پردازش")
    p2=  f"{message.voice.file_id}.ogg"
    result = model.transcribe(p2)
    send = result["text"]
    print(send)
    bot.send_message(message.chat.id  , send)

@bot.message_handler(commands=['help'])
def send_help(message ):
    bot.reply_to(message , "برای حل مشکل به این ایدی پیام دهید ")
    bot.send_message(message.chat.id ,"@yousef")
    menu1 = types.ReplyKeyboardMarkup(resize_keyboard=True)
    item1= types.KeyboardButton("about us")
    item2 = types.KeyboardButton("tell")
    item3 = types.KeyboardButton("id")
    menu2.add(item1 , item2 , item3)
    bot.send_message(message.chat.id ,"chose one ", reply_markup=menu2)

bot.polling()
